name: Environmental Communication
favicon: null
layout_spectrum: 0.15625
typography_spectrum: 0.59544
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#030305'
    - '#043287'
    - '#30664c'
    - '#8d5f38'
    - '#259781'
  brandStrength: 0.939936745679006
  lightness: 0.0726405659224838
  saturation: 0.8105987971648574
  rhythmicContrast: 0.00548345479182899
purpose: []
