name: Environmental Communication
favicon: null
layout_spectrum: 0.93159
typography_spectrum: 0.59544
title: ENVIRONMENTAL COMMUNICATION
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#030305'
    - '#043287'
    - '#30664c'
    - '#8d5f38'
    - '#259781'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
