name: ENVIRONMENTAL COMMUNICATION
favicon: null
layout_spectrum: 0.67461
typography_spectrum: 0.1525
title: Exploring Human Relations With Nature
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#030305'
    - '#043287'
    - '#30664c'
    - '#8d5f38'
    - '#259781'
  brandStrength: 0.875
  lightness: 0.1875
  saturation: 0.25
  rhythmicContrast: 0.75
purpose: []
